### ISSUE TITLE
Causes incompatbility with GSXPro

### ISSUE THREAD

**Issue by Jakedrew1902** [markszutor/LVFR-A318-FBW-Compatibility-Mod#2]
GSX Pro recognises both the LVFR A318 and FBW, however not the hybrid this mod produces. Since FBW uses a custom parking brake variable where the LVFR A318 doesn't, GSX can't recognise that the parking brake as set as the mod creates a hybrid variable that gsx doesn't recognise (Similar to the other lvfr aircraftwith fbw compatibility mods).

**Comment by TJCAviation** [comment]
This is a WIP mod and not released. We have internal GSX Profiles that work which will come with the final product.

Please don't use GH builds and open tickets if it isn't released, it isn't meant for public use.
